### ISSUE TITLE
Create NodeJS-based OpenAPI interface on data

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#1030]
Possible NPM package for creating R data frames:

https://www.npmjs.com/package/deployr

**Comment by Mak-NOAA** [comment]
Thanks @toddhay-NOAA 

Look forward to working on this with you @jimfellows-NOAA

**Comment by Mak-NOAA** [comment]
@toddhay-NOAA do we have any requirements already or need to do some requirements gathering?

**Comment by SaOgaz-NOAA** [comment]
@Mak-NOAA, @jimfellows-NOAA, is this still a thing that's gonna happen? (@BHHorness-NOAA)

**Comment by Mak-NOAA** [comment]
I don't even remember this. @jimfellows-NOAA is this for getting data warehouse data?

**Comment by jimfellows-NOAA** [comment]
I think the general idea was to create a library usable in R code so that observer analysts or whoever could pull data straight from couch into a dataframe.  I think with our use of Apache Drill + MongoDB the need for this kinda goes away, as there are already R packages that do this (see [sergeant](https://cran.r-project.org/web/packages/sergeant/index.html, [DrillR](https://cran.r-project.org/web/packages/DrillR/index.html)).  We can probably close this out, don't think there's anyone waiting on this specific functionality at this point.

**Comment by SaOgaz-NOAA** [comment]
Thanks @jimfellows-NOAA! Closing...
