### ISSUE TITLE
OTS update late notice text

### ISSUE THREAD

**Issue by scottleach-NOAA** [nwfsc-fram/boatnet#1131]
Update sub 24 hour notice with the following message

Trip start date is less than 48 hours from now! Observer is required and will be provided ASAP but trip may be delayed up to 48 hours.

**Comment by sethgerou-noaa** [comment]
This language makes it sound like the trip is definitely selected for coverage, but the selection doesn't currently happen until the trip is created (submitted).  Seems like we could either change to "if trip is selected for Observer coverage, the trip may be delayed by..." or put a warning on the trip after it has been created (rather than when the date is picked).  

Not totally sure how this will work yet, but when we're displaying whether or not the next trip is selected, we could display the 48 hour warning only when the next trip IS selected.

**Comment by scottleach-NOAA** [comment]
Good point, I like your idea of changing the text to 

Trip start date is less than 48 hours from now! If selected for observer coverage an observer will be provided ASAP but trip may be delayed up to 48 hours.
