### ISSUE TITLE
install git secrets

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#125]

**Comment by wsmith-nwfsc** [comment]
Seems to require admin access to install this, and I don't think this actually does anything useful for us (it prevents AWS keys from being installed.)

Instead, let's use git hooks. In your .git/hooks folder, you can rename pre-commit.sample to pre-commit and it will enable pre-commit hooks. We should use that as a starting point for these kinds of rules.

**Comment by wsmith-nwfsc** [comment]
Created #126 along those lines

**Comment by toddhay-NOAA** [comment]
roping @bjamesvERT into this conversation as he was the one who investigated git-secrets.  Let's agree as a group first before migrating to git hooks.

**Comment by wsmith-nwfsc** [comment]
Makes sense, and I think we will want both ideally.

**Comment by bjamesvERT** [comment]
@toddhay-NOAA Yes, admin is required to install on Windows (I'd put that in the commands for [Windows setup](https://github.com/nwfsc-fram/boatnet/blob/master/README.md#development-setup ), but didn't specifically mention it at the top)

Yeah, both simple hooks & git-secrets could be complementary. Detecting credentials is challenging & no one approach is perfect.

Git-secrets uses the model of 1) identifying bad things via patterns, not file names, so as to catch content even if file is accidentally renamed for testing, etc. and 2) acknowledging false positives via individual filenames+patterns.
Under this model, thing to do for dbConfig.json would be create a regex to match the content, add to a repo file & update setup instructions with: `git secrets --add-provider -- cat /path/to/repo/patterns/files`

@wsmith-nwfsc Looks like they've changed to AWS only, out of the box.  In May, git-secrets came with three AWS-specific rules and one general-purpose pattern to find potentially problematic 20cha alphanumeric strings (false positives [greatly increase below 20cha](https://github.com/dxa4481/truffleHog#how-it-works)), but looks like in October the general was [tightened to specifically target AWS access tokens](https://github.com/awslabs/git-secrets/pull/89) ... because people kept getting too many FPs.

Adding general pattern back will require adding a setup step: `git secrets --add '[A-Z0-9]{20}'`
