### ISSUE TITLE
Observers in Oracle not found associated with trips in CouchDB

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1280]
Observers Ken Grimes and Robert Bettin are not associated correctly with their wcgop-trip documents.

The Ken has 193 trips observed in Oracle dating back to 2013, and Robert has 287 trips observed dating back to 2014.  The wcgop-trip documents are in master-dev on the DEV Couch server, but no observer sub-document exists.

Example: trip_id=38123, couch_trip_id=916975c39b316dfdbece7e2c4153dc4a

Other examples going back to 2017 can be found here:
\\nwcfile\FRAM\Users\James.Fellows\oracle_to_couch_qc\missing_observers_20200131.xlsx

**Comment by NickShafferNOAA** [comment]
Turned out to be a simple issue. Query I am using to get all observers has an extra check beyond just checking if the user_id was in trips table, and that check failed for those two particular users. Talked with Neil about this and the two cases here are caused by changes in a user's role from observer to something else (debriefer, lead observer, etc), therefore were missed in the query. Also found out by him that we need to include any users with the role of "lead observer" as well as just "observer". 

Making that change in the etl code now for future data pulls.
