### ISSUE TITLE
Departure and return dates mismatch between Oracle and Couch?

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/boatnet#1281]
There seems to be a mismatch between the departure and return dates in Couch and Oracle.  I think it is related to timezone offsets changing due to daylight savings, but I could be confused.

Both Oracle and Couch appear to use -8 (PST) and -7 (PDT) time offsets, but compared side by side they don't look consistent:

_Example 1:_
Trip_ID = 40525
CouchID = 916975c39b316dfdbece7e2c4195f6b1
CouchReturnDate = "2019-10-30T00:00:00-07:00"
OracleReturnDate = "29-OCT-19 11:00 PM PDT"
OracleReturnDateUTC = "30-OCT-19 06.00 AM"

_Example 2:_
Trip_ID = 39303
CouchID = 916975c39b316dfdbece7e2c416251d1
CouchReturnDate = "2019-06-12T00:00:00-07:00"
OracleReturnDate = "11-JUN-19 11:00 PM PDT"
OracleReturnDateUTC = "12-JUN-19 06.00.00.000000 AM"

The Oracle UTC conversion was done using the SYS_EXTRACT_UTC(TIMESTAMP) function. More examples from 2019 where the offset caused the Oracle and Couch dates to register on different days are stored in an excel file on the shared drive:
\\nwcfile\FRAM\Users\James.Fellows\oracle_to_couch_qc\tripdate_mismatches_2019_20200131.xlsx

_Bonus Example 3_ (this may confuse things, not sure if this is the same issue here):
Trip_ID = 40751
CouchID = 916975c39b316dfdbece7e2c418e0f8b
CouchReturnDate = "2019-12-**19**T21:30:00-08:00"
OracleReturnDate = "**18**-DEC-19 09:30 PM PST"
OracleReturnDateUTC = "19-DEC-19 05.30 AM"

**Comment by NickShafferNOAA** [comment]
Did some investigating on issue for example 1&2, the couch returnDate attribute is an hour off due to something under the hood of javascript itself, it seems. Upon querying oracle and storing the raw result, it's already an hour off from the database record. I'm not sure _why_ this is happening yet, but I've narrowed down _where_ it's happening.

As for the second issue (example 3), I found that the updatedDate on the document did not match the updated date in oracle. I pulled the record down and did the same transformation to that field (and then some) and never wound up with a different day. I can only assume that the return date in oracle was edited shortly after this data was pulled over.
