### ISSUE TITLE
ETL OBSPROD Trips Data

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#132]
- [x] Trips
- [x] Hauls
- [x] Catch
- [x] CatchSpecies
- [x] Specimens
- [x] Baskets

**Comment by toddhay-NOAA** [comment]
@NickShafferNOAA, please provide an update as to this task.  We were targeting having this completed, or close to completion, by today, but it's unclear how far along you are in the process.

**Comment by NickShafferNOAA** [comment]
I have the code for the species data prototyped and written up (some possible changes to make but I dont think are crucial for this moment), but the bulk of it is written. I've spent the last few days doing this and also refactoring to use couchdb views instead of mango indexes as was discussed Monday. I am currently running tests and working out minor kinks here and there that were caused from that switch and the changes to the models lately.

I still need to test/run through the new code. I am focusing on that today and going to try to get a full bulk pull done overnight tonight, assuming no major issues crop up.

**Comment by wsmith-nwfsc** [comment]
I created #276 which describes how we'll extract lookups from this master DB.

**Comment by wsmith-nwfsc** [comment]
Great @NickShafferNOAA ! 
We'll definitely have some review feedback as we look at the imports. I think I'm looking at old import data, so just an example of the kind of stuff we'll probably be fiddling with (looking at my clone of your large nick-test database for this example)
```
"type": "Vessel" // this should be lowercase
  "coast_guard_num": "509680",
  "state_reg_num": null,  // In general, do not create a null record, just leave off state_reg_num
```

**Comment by NickShafferNOAA** [comment]
Another Update: I've successfully ran a small portion (~1000 catch documents) of data and seems to be successfully querying and building the specimen and basket data

 @wsmith-nwfsc @toddhay-NOAA  I'm still not 100% confident I fully understand the translation from oracle tables into the wcgop-catch-species model, but I wrote the scripts for how I currently understand it. If could, I'd like to get together some time to review that specific piece of the code / the translated data in couchdb for confidence. If I do need to correct that piece, it shouldn't be a very time consuming task. 

The addition of the species data to the script is affecting the runtime by a much larger margin than I thought it would, the 1000 catch records took 3 minutes, out of the million records in OBSPROD. As it stands now, a 100% initial bulk pull won't finish in a single night. I'm going to review pieces of the script and see if there's any obvious changes for efficiency I can make.

**Comment by wsmith-nwfsc** [comment]
If you're not already, be sure you're using the bulk operations:
https://github.com/apache/couchdb-nano#dbbulkdocs-params-callback

**Comment by NickShafferNOAA** [comment]
update on this: Finished logic for pulling in entire tables and sorting them into dictionaries to further minimize oracle connections. Ran a successful test from start to finish, the initial queries add about 15 minutes as expected, but drastically reduces initial bulk pull time, and will only load data that has been updated or associated records updated. 

ETLing all the haul/catch/species data is down to 40 minutes.  I havent made this efficiency change to Trip data yet (since Trip data wasnt the bottleneck before) but it will be done as I add the mmsbt, hlfc, and brd data.

**Comment by toddhay-NOAA** [comment]
Nice job on this @NickShafferNOAA
