### ISSUE TITLE
Cruise API: Configuration for Local Development

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#1465]
Problem Summary:
 The currently deployed cruise API requires a JWT that is signed with the same certificate that is used by the login server. (Note: dev-auth-server uses its own, temporary certificate, so JWT's from dev-auth server will be rejected by the cruise API server.)

To, we need to determine a way to get a valid JWT to a cruise API server. I think Seth would have this same limitation, so curious to hear what he's using.

Some possibilities:

* Use actual dev auth for testing, this creates Cruise ID's in couch dev DB

* Mock a cruise API server (considerations for what happens in the couch dev DB)

**Comment by melinashak-noaa** [comment]
Make the changes to the following files to connect to the actual dev auth server rather than the local/fake auth server.

**vue.config.js**
comment out:
  devServer: {
    proxy: 'https://localhost:9000'
  },

**config/dbConfig.ts**
add apiUrl: 'https://nwcdevmeow1.nwfsc.noaa.gov:9000'

The file should look like:
import { DBConfig } from '@boatnet/bn-auth';

// Leave unchanged for Dev - overwritten in Prod
const dbConfig: DBConfig = {
  // apiUrl: 'https://localhost:9000'
  apiUrl: 'https://nwcdevmeow1.nwfsc.noaa.gov:9000'
};

export default dbConfig;

**Comment by wsmith-nwfsc** [comment]
That will work for now, thanks!

I think I want to add a cruise API to the dev-auth-server, so we can use test accounts, but no rush on that.
