### ISSUE TITLE
Trip button on HOME page doesn't do anything. After pressing all 3 buttons I got the error attached

### ISSUE THREAD

**Issue by ericbrasseur-NOAA** [nwfsc-fram/boatnet#1692]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/45770674/85082028-8ac12500-b182-11ea-83db-6de1215a0e20.png">

Using a iMac, safari
In captain mode, the buttons under the logo 
the trips button doesn't seem to do anything. and later resulted in 
TypeError: undefined is not an object (evaluating 'this.vessel.activeVessel.coastGuardNumber')

DISMISS

@sethgerou-noaa @scottleach-NOAA @neilriley-NOAA @johnlafargue-noaa

**Comment by ericbrasseur-NOAA** [comment]
Might be a site issue, trips tab seems to be not working, will try logging in and out.

**Comment by ericbrasseur-NOAA** [comment]
@sethgerou-noaa 
FYI, Trips is still not working for me.
<img width="1170" alt="Screen Shot 2020-06-25 at 11 58 32 AM" src="https://user-images.githubusercontent.com/45770674/85782165-40d4c380-b6db-11ea-8730-29b58c14322a.png">

**Comment by sethgerou-noaa** [comment]
Just trips?  Or the same issue you experienced on the call, where no data was loading from the DB for periods of time?

**Comment by sethgerou-noaa** [comment]
@ericbrasseur-NOAA  I found a doc in your individual couch userdb that potentially could have caused an intermittent db connection issue.

You may need to log out and back in again to sync your userdb.  
If that doesn't work/change anything, I'd suggest clearing your cache - in Chrome: tools/more tools/advanced - select 'All Time' and clear everything except "Passwords and Other Sign In Data".

Let me know if that works / if the issue persists.

**Comment by sethgerou-noaa** [comment]
@ericbrasseur-NOAA  actually, now that I think about it - if this doc is indeed the culprit - it's a bit trickier to remove.  You'll need to clear your cache on all devices you've used to log in to observer-web, otherwise the doc will just re-sync to master the next time you log in with that device.  

@wsmith-nwfsc I'm thinking this may be a holdover from when we were having issues with a userdb pouch view getting synced to couch userdb and then masterdb.  The issue was resolved some time ago (can't remember how) but if one of Eric's devices has a cache that's been around for quite some time, it may still have the old view doc.

**Comment by ericbrasseur-NOAA** [comment]
It seems back on my ipad but not on my imac, I cleared history and the docs all reloaded.  got the same TypeError: undefined is not an object (evaluating 'this.vessel.activeVessel.coastGuardNumber') after clicking a few things.

**Comment by sethgerou-noaa** [comment]
@SaOgaz-NOAA  I believe the error Eric is getting - TypeError: undefined is not an object (evaluating 'this.vessel.activeVessel.coastGuardNumber') - is coming from the declarations page.

repro steps:
-on Home page make sure Captain Mode is not checked.
-go to Trips page
-do not select a vessel, or if one is selected, clear the selection
-go to Declarations page and don't do anything
-go to Home page

note: selecting a vessel on the Declarations page then going to Home page produces a slightly different error.

The Declarations component seems to throw errors when it is created without an active vessel.
This doesn't appear to affect the behavior of the page - so maybe just console log the error instead of putting it in an errorAlert - can't imagine that sort of error being of any use to a user).

I still have not been able to reproduce the primary issue this ticket describes where user is unable to do anything in the app for a period of time after receiving this error.  Not sure whether it's related.

**Comment by SaOgaz-NOAA** [comment]
@sethgerou-noaa  will take a look at this tomorrow and probably implement your fix suggestion about just console logging the error.  I do feel like I noticed a weirdness I had in a similar sounding bit of code a few months ago, and I don't remember if I fixed it or not.

**Comment by SaOgaz-NOAA** [comment]
@sethgerou-noaa, looks like that error pop up is fixed. Should I be getting a blank screen for trips BTW?

**Comment by sethgerou-noaa** [comment]
@SaOgaz-NOAA no, you shouldn't.  that's a different issue - think I know the cause / have a fix though.
