### ISSUE TITLE
elogbook -Count and Length fields in Catch entry should not be red unless a priority or protected species is entered

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1909]
@sethgerou-noaa if  Catch entry if 'estimated weight' then Count and Length fields should not be red for all species. The way this functions now it implies they are required all the time when they are not. Wondering if the 'Weight Calc Method' fields should be moved before the weight, then if the entry is Est Weight then don't highlight red, unless a priority or protected species exists.

![image](https://user-images.githubusercontent.com/31421964/93639003-2a25cc00-f9ad-11ea-9439-89d7cecdefe1.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA these are red due to a number value being required, and '' an empty string, isn't a number.  This has been fixed and should be reflected in prod as soon as the latest build finishes (~ 5 minutes).

I'm not sure I know all the priority species requirements...

some validations I can think of:
if count is greater than 1, the user should not be able to enter a length, but a weight is ok
if a length is entered, count must be 1 or not entered
if species is pacific halibut, length and time on deck are required

any others?

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the 3 validations you listed out are good. 

for priority spp. if weight exists then a count >= 1. However, I could envision a scenario where they don't know the count so maybe they just get a warning and we require a comment.
