### ISSUE TITLE
EM Logbook species codes

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1978]
@NickShafferNOAA @sethgerou-noaa 

Where does logbook species code come from? some of these don't appear to be the PacFIN code.  For example Whale Unid has a code = MIXED. That can't be right. Also, is there an isEM flag associated with these codes for logbook. I didn't see this in couch, but then again I am not sure I am looking at the right view. 

![image](https://user-images.githubusercontent.com/31421964/97333302-a925e400-1838-11eb-9c01-93fe08e68807.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA @NickShafferNOAA @melinashak-noaa 

I'm not sure how the data was populated/created, but as far as the tripsApi docs are concerned, the logbook (speciesCode) "lookup" property displays whatever is stored in **"pacfinSpeciesCode"** in the taxonomy-alias or catch-grouping doc.
(and the review speciesCode "lookup" property displays what is in the **"wcgopSpeciesCode"** property.

Anything that's showing up on the tripsApi docs lookups page has **"isEm": true**.  The api docs fetch all EM lookups via the
**TripsApi/all_em_lookups** couch view.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA shoot, wrong button.  didn't mean to close.  
If there are a few of these that need their pacfin code corrected - I'm happy to help if you like.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa Thanks for the feedback.  Can you change the following codes to  **"isEm": false**?  These codes aren't needed for EM at this time.


PUGT | Puget Sound Rockfish

URCK | Semaphore Rockfish

MSC2 | Slender Codling

MIXED | Whale Unid

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA Done.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa sorry need to re-open this one. 

these Non-IFQ Specie are listed on the fixed gear logbook but never made it into the lookup. 

CODE COMMON NAME
Non-IFQ Species
CBZN Cabezon
GRDR Unspecified Grenadiers
OCTP Octopus
CMCK Chub/Pacific Mackerel
JMCK Jack mackerel
UMCK Unspecified Mackerel
BSKT Big Skate
LSKT Longnose Skate
SKAT All Other Skates and Rays
DSRK Spiny Dogfish
SSRK Soupfin Shark
OSRK Other Shark
WEEL Wolf Eel
WSTG White Sturgeon
UTCR Tanneri Tanner Crab
GGRD Giant Grenadier
GREN Pacific Grenadier
RATF Spotted Ratfish

**Comment by sethgerou-noaa** [comment]
@NickShafferNOAA 
Looks like some data translation needs to happen with these.

CBZN Cabezon for example has pacfinSpeciesCode and wcgopSpeciesCode still in taxonomy, and does not have the "isEm" property.

fyi @neilriley-NOAA

**Comment by sethgerou-noaa** [comment]
@NickShafferNOAA 
also:
SHAD Unsp. Shad
and
PHRG Pacific Herring
I'm not seeing these at all - they need to be added to couch and set to isEm: true

**Comment by NickShafferNOAA** [comment]
@neilriley-NOAA Some of the items appeared already in the database, I have added the ones that were not, and removed a couple duplicates.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  These still don't show in the logbook lookup in Obs-web. assuming the isEM flag needs to be changed for the list in this ticket

**Comment by sethgerou-noaa** [comment]
@NickShafferNOAA @neilriley-NOAA 
Still seeing several issues with these:
URCK Semaphore Rockfish - 2 taxonomy-alias docs with URCK code - Semaphore Rockfish and Rockfish Unident. / Spotted Rockfish UNID (this one has isEm: true but should be isEm: false)
CBZN Cabezon - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode
GRDR Unspecified Grenadiers  - catch-grouping doc has old "code" attribute instead of pacfinSpeciesCode, missing wcgopSpeciesCode, missing isEm
OCTP Octopus - catch-grouping doc has old "code" attribute instead of pacfinSpeciesCode, missing wcgopSpeciesCode, missing isEm
CMCK Chub/Pacific Mackerel - tax-alias doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode
JMCK Jack mackerel - tax-alias doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
UMCK Unspecified Mackerel - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
BSKT Big Skate - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
LSKT Longnose Skate - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
SKAT All Other Skates and Rays - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
DSRK Spiny Dogfish - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
SSRK Soupfin Shark - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
OSRK Other Shark - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
WEEL Wolf Eel - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
WSTG White Sturgeon - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
UTCR Tanneri Tanner Crab - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
GGRD Giant Grenadier - tax-alias doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
GREN Pacific Grenadier - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
RATF Spotted Ratfish - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
SHAD Unsp. Shad - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode, missing isEm
PHRG Pacific Herring - catch-grouping doc has old "code" attribute, missing pacfinSpeciesCode and wcgopSpeciesCode

Where available pacfinSpeciesCode and wcgopSpeciesCode should be in every taxonomy-alias and catch-grouping doc.
All taxonomy-alias and catch-grouping docs should have isEm attribute - set appropriately,

**Comment by melinashak-noaa** [comment]
To add onto this, believe a taxonomy-alias doc for species code: USRK  (unidentified shark) needs to added 
https://github.com/nwfsc-fram/boatnet/issues/2022

**Comment by NickShafferNOAA** [comment]
Added flags, fixed / added codes to all except a few.

While I was double checking, I noticed Hydrolagus melanophasma is missing from the couch database, I can't seem to find an ITIS entry for this, must've flown under the radar. 

These codes are listed under old wcgop catch category records but no species, I cannot seem to find any wcgopSpeciesCode for any of these ones: 

GRDR
OCTP
CMCK
UMCK
SKAT
UTCR
GGRD
GREN
SHAD
USRK

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA Correct. Those codes were only used as Catch Categories by observers and may not have a corresponding WCGOP code. Did these get added to Couch?  

cc @sethgerou-noaa

**Comment by NickShafferNOAA** [comment]
They are in couch right now. So do those specific ones not need a WCGOP code, or does one exist somewhere for them?

**Comment by neilriley-NOAA** [comment]
Some of them have wcgop codes for example. 

OCTP = Octopus Unid = wcgop species codes = 60




Octopus Unid
--




Octopus Unid
--

**Comment by neilriley-NOAA** [comment]
@NickShafferNOAA @sethgerou-noaa @melinashak-noaa @BHHorness-NOAA 

Maybe it is just me, but I am having hard time tracking PacFIN codes, wcgop species, codes, alias, old catch category codes and everything else in the Couch taxonomy. Can we create a view or some way to visualize how all these relate to one another in a table format?  It seems like this stuff is all over the board.

**Comment by NickShafferNOAA** [comment]
The inflexibility of looking at the data is a big downside of couch. I can create some individual views that enable easier review at a glance of individual attributes if that would help. Do you use Fauxton to look at couch data?

**Comment by neilriley-NOAA** [comment]
Yes, I am using Fauxton to look at couch. Individual views may help but a crosswalk with everything may be more useful. I would imagine we will eventually need a simple way for user WCGOP staff to view all the taxonomy via the app.

**Comment by NickShafferNOAA** [comment]
I believe the original issues for this ticket are solved, following up with https://github.com/nwfsc-fram/boatnet/issues/2085
