### ISSUE TITLE
FG calc not working for discard data when count is calculated

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#1987]
@sethgerou-noaa @melinashak-noaa 

Data submitted for fixed fear sablefish discard with only a count didn't calculate a value. Example trip 100265, expected Sablefish discard = 2.9 lbs.

![image](https://user-images.githubusercontent.com/31421964/97605511-f1c1d680-19cb-11eb-8de7-50d0349e664a.png)

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA @melinashak-noaa 

I believe this stems from an inconsistency in property naming - the api definition expects speciesCount, but in your submitted data it's listed as catchCount - which name do we prefer?

Also, the length property is currently just called 'length', but I'm worried that's a reserved word and unexpected things may happen (if the value is '37', catchrow.length may be 2, as '37' is 2 characters long).  I'd propose we change to either catchLength or speciesLength to match whatever we decide on the above.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I agree let's go with speciesCount,  speciesWeight, &  speciesLength

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA @melinashak-noaa 
I've made all the updates to speciesCount, speciesWeight, & speciesLength, and have manually changed the property names in all catch docs in PROD.  I don't believe Neil uses DEV.  Melina, so that you are aware, I have not updated the catch docs in DEV, so adding a review for a tripNum that already has a logbook, but with old property names likely will result in errors.  I'll probably end up updating some catch docs and deleting the rest.

FYI: I'm working on validations for the e logbook, but at the moment it's possible to submit logbook data with missing required info.  the submission message should now say the submission was not accepted, but it does not yet warn of invalid field values.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa correct. I am only using Prod for testing. Thanks for making all these fixes.
