### ISSUE TITLE
Create error validation when netType is missing

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2054]
@melinashak-noaa @sethgerou-noaa 
Create error validation when netType is missing and gear = trawl

Nettype should be required. example trip = 100271

![image](https://user-images.githubusercontent.com/31421964/100288857-7a308a00-2f2c-11eb-9e18-2ceb6a599f7f.png)

**Comment by melinashak-noaa** [comment]
Created fix, deploying code now https://github.com/nwfsc-fram/TripsApi/commit/6986e6cc0652cdd34bf351d6f56168f089e04556

**Comment by melinashak-noaa** [comment]
okay this check is out in production now

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa I don't think this is working. I am submitted a test trip 100271 with a missing netType for haul 2 and it didn't produce an error.

**Comment by sethgerou-noaa** [comment]
@neilriley-NOAA While the netType presence validation was properly in place, apparently the default behavior is to accept an empty string as valid, so "netType": "" (what you submitted) was accepted because the "netType" attribute was present.  I've added "allowEmpty": false to most presence validators.  Should be working in PROD now.
