### ISSUE TITLE
Obs-web does not display multiple fish tickets in EM

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2178]
Submitted 2 fish tickets for trip 100275, the UI only displays the most recent ticket.

	"fishTickets": [{
		"fishTicketNumber": "EE123456",
		"fishTicketDate": "2021-02-03T00:00:00Z",
                "fishTicketNumber": "EA999999",
		"fishTicketDate": "2021-02-04T00:00:00Z"

![image](https://user-images.githubusercontent.com/31421964/108135812-a2341300-706d-11eb-8411-ea3ee33135d8.png)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the issue was with in the JSON. It works when formatted properly.

"fishTickets": [{
			"fishTicketNumber": "EE123456",
			"fishTicketDate": "2021-02-03T00:00:00Z"
		},
		{
			"fishTicketNumber": "EA999999",
			"fishTicketDate": "2021-02-04T00:00:00Z"
		}

My concern is there is no way to prevent someone from doing what I did in my initial upload. Thoughts on how to enforce this?

**Comment by sethgerou-noaa** [comment]
As you submitted originally would be nearly impossible to detect.

As soon as the tripsApi receives the JSON, all it sees is the second set of values...
"fishTicketNumber": "EA999999" over-writes "fishTicketNumber": "EE123456" because the property name "fishTicketNumber" is the same.

This happens as soon as the JSON is parsed, so I haven't thought of a way to detect / warn.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa that makes sense. It most likely won't be a big deal, but thought I would check. I will close this ticket.
