### ISSUE TITLE
Trip Details Screen

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#220]
- [x] Add Left/Right arrows for advancing/returning between first and second pages
- [x] Enable multiple permits to be entered
- [x] Add Date/Time selector (ruggedized touch screen friendly) for Departure Date/Time
- [ ] Add auto-complete for lookup value fields (departure port)
- [ ] Do not stretch the numpad popup
- [ ] Departure Date - Auto-close Date picker on new date selection
- [ ] Departure Date - Remove whitespace on the right-side of the popup
- [ ] Persist data

**Comment by melinashak-noaa** [comment]
Currently working on the add trip functionality. We'll have to figure out what we should use for friendly tripId. Currently we're getting the number of trips then adding one and using that as the tripId. So for example if there are 18 trips the new trip gets assigned tripId 19. We can explore if we would like to stick with this or use something else.

**Comment by sethgerou-noaa** [comment]
I'm using the same code to get trips in obs-web.  
Existing trips are listed descending by tripNum, so I'm taking pouchDBTrips[0].tripNum, and adding 1 to that to get my new trip number - so I don't have to worry about the number of trips messing up the tripNum sequence.

**Comment by toddhay-NOAA** [comment]
The screen is looking good @melinashak-noaa.  It seems like the only outstanding item is to not stretch the numpad popup.  Is that doable?

**Comment by melinashak-noaa** [comment]
so haven't found an easy way to do this. Was hoping there was a parameter i could just pass to the keyboard and adjust the size, but seems like this keyboard doesn't support that. https://github.com/icebob/vue-touch-keyboard 

would have to do more investigation to figure out how to resize it.

**Comment by wsmith-nwfsc** [comment]
I think, ideally, instead of overlapping the UI, the keyboard would be inside its own higher-level UI component (with an opaque background) that "pushes up" the rest of the screen contents. The keyboard would probably size to fit this higher level UI component.
E.g. avoid stuff like this:
![image](https://user-images.githubusercontent.com/12972097/57641321-9c8ccd80-7569-11e9-86f0-5bedc8353e80.png)

**Comment by ericbrasseur-NOAA** [comment]
The time entry is a bit clunky. To use it I have to highlight and enter a time.  The default should be "now" when clicked.

**Comment by ericbrasseur-NOAA** [comment]
On the t-800, the keyboard covers most of the fields and must be dismissed to use, also if in tablet mode the windows keyboard pops up by default.  We will need to pick a keyboard and suppress
![Screenshot (9)](https://user-images.githubusercontent.com/45770674/60849752-052aac00-a1a1-11e9-8a43-387b33def96e.png)
![Screenshot (10)](https://user-images.githubusercontent.com/45770674/60849753-052aac00-a1a1-11e9-9c25-9bffe3ac99a6.png)

 the others.

**Comment by ericbrasseur-NOAA** [comment]
Skippers name should be a lookup value filtered by vessel.

**Comment by ericbrasseur-NOAA** [comment]
Balance fields and scale on screen rather than having white space to the right.  Having the fields all in a row makes data entry more difficult when the keyboard pops up. See OPTECS layout (it's not quite 100% balanced though). All fields should be visible at a screen size of 1280 X 800 at 125% scale without scrolling.  Scrolling is not desired on deck.
