### ISSUE TITLE
Create Fish Ticket Component

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#224]
Need a Fish Ticket component for embedding into Trip Details, per the mockup:
![image](https://user-images.githubusercontent.com/12972097/54853010-c7664e00-4cab-11e9-8361-0d920462e817.png)

**Comment by ericbrasseur-NOAA** [comment]
Field use has found a small user issue with the current OPTECS method for fish tickets.  Some users were entering data but not adding the fish ticket.  The process is different then almost everything else in OPTECS since we normally save all data once it is typed.  Consider ways to retain the data if a user does not click add.

**Comment by melinashak-noaa** [comment]
Got this working and modified to show calendar when the fish ticket menu opens
