### ISSUE TITLE
logbook fish ticket date is incorrect

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2370]
uploaded fish ticket date = 6/24/21 but displayed as 6/23/2021 in the app

"fishTickets": [{
		"fishTicketNumber": "TEST12346",
		"fishTicketDate": "2021-06-24T00:00:00Z"
	}],

![image](https://user-images.githubusercontent.com/31421964/123341631-23f7e980-d503-11eb-8d90-89234b01b333.png)

**Comment by sethgerou-noaa** [comment]
The time you submitted via the api submission portal ("2021-06-24T00:00:00Z") doesn't have a time zone offset, so that time, when displayed in Seattle does occur on 6/23/2021 (at 5PM).  To display as 12AM on 6/24 it technically should be "2021-06-24T07:00:00.000Z".

If we think this will be a common error, it's easy enough to display trips/catch api dates in UTC, which ignores the time zone info, but we should think about whether we want to expect the correct time zone in dateTime objects, always ignore it for dates, or some other policy.  Could get confusing to sometimes ignore it - everything that's entered in obs-web and the new tablet app will always have a timezone offset (whether it has an entered time or not).

**Comment by neilriley-NOAA** [comment]
that makes sense. this time zone issue recently came up with the analyst and they need the correct time zone. my initial thought is to include the offset to avoid confusion.
