### ISSUE TITLE
Fix boatnet-keyboard Autocomplete on Trips Details

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#318]
The autocomplete on Trips Details doesn't quite behave well with the onscreen keyboard.
There are a lot of errors in the console log, so that'd be a starting place to figure out what's up.

**Comment by melinashak-noaa** [comment]
Got rid of the error in the console by adding a null check
**Before was getting this error**: Error in v-on handler: "TypeError: Cannot read property 'target' of undefined"
**Code to fix:** 
if (event) {
      this.$emit('displayKeyboard', event.target);
 }

Resolved another issue where the text was getting reset to the previously selected option when using the on-screen keyboard. You would type, then sometimes the text would get reset and everything you just had just entered disappeared. Resolve this by setting preventClickEvent = true in the BoatnetKeyboard component. 

Currently working on a final issue where the options menu for q-select keeps disappearing while using the on screen keyboard. Was looking into the vue events and see that q-menu emits a hide event, then on the next keypress it emits a show. Keeps toggling between these two states so with every keypress the menu is shown, then hid, shown, then hid. 
Believe it may be caused by the q-select losing focus. On the first keypress it gains focus and shows the menu. Then when i select a character on the keyboard it loses focus and hides the menu. On the next keypress it regains focus and shows the menu. So looking for a way to modify this behavior.

**Comment by melinashak-noaa** [comment]
![image](https://user-images.githubusercontent.com/44685558/57034879-83992980-6c05-11e9-823f-a3f997e362f9.png)

**Comment by wsmith-nwfsc** [comment]
Interesting. The autocomplete functionality we have for the q-select is probably what's causing all those redraws (hide/show etc)

**Comment by melinashak-noaa** [comment]
https://github.com/nwfsc-fram/boatnet/pull/336

**Comment by melinashak-noaa** [comment]
close for now, there's still the issue with hiding and showing of options, but got rid of the console errors
