### ISSUE TITLE
Haul Details - Beaufort Scale + Gear Type look like their button groups are split, make them appear as one group

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/boatnet#473]
Current when looking at the Beaufort Scale button group, it looks like there are 2 groups of 5 buttons.  Please make it all look like a single group of 10 buttons.

This is similar for the Gear Type where it looks like 2 groups of 4 buttons.

FYI:  Possible Vue Quasar technologies seem to be Button Group or Button Toggle for implementation.

**Comment by melinashak-noaa** [comment]
So for this one, was experimenting with showing the button group on two lines. If you make your screen narrower then it should show up on two lines, but if it's too wide then the weird split thing shows up. For now I'll just put it back to one line since it doesn't look like we'll be needing two columns on these pages.
