### ISSUE TITLE
Prevent PouchDB data stores from conflicting with each other

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#478]
Currently when one has the Obs-Web and Obs-Trips apps both open at the same time, the applications get confused in terms of their data, and often don't show the data properly.  Need to deconflict and prevent this from happening.

**Comment by sethgerou-noaa** [comment]
This also happens with two simultaneous Obs-Web windows.  Not sure about 2 Obs-Trips windows.

**Comment by toddhay-NOAA** [comment]
@wsmith-nwfsc, please add this to your list of infrastructure tasks to complete this week.

**Comment by wsmith-nwfsc** [comment]
I'm suspecting this may be because of vuex-persist interfering with itself. Looks like we're both using the same key:
```
const vuexLocalStorage = new VuexPersist({
  key: 'vuex',
  storage: window.localStorage
});
```
So, going to try changing that to obs-trips and obs-web instead of 'vuex' and seeing what that does.

**Comment by wsmith-nwfsc** [comment]
This is an unusual issue because localStorage is limited to whatever the current domain is (e.g. nwcdevfram.nwfsc.noaa.gov) to prevent conflicts & evildoing, but since we share that domain (using different ports instead of different endpoints) and share localhost, we don't have that advantage.

I've changed the vuex-persist to store in separate namespaces which I think will fix this. After applying this you'll have to reload the page from login, as the automatic vuex store persistence is moved.

@sethgerou-noaa when you get a chance, this is ready to check to see if you can repro whatever issues you've noticed.

**Comment by sethgerou-noaa** [comment]
In testing (with the latest code), I've experienced data failing to load from couch, pouch seems unaffected, when 3 instances of any combination of Obs-Web and Obs-Trips are running simultaneously.  

- 2 seems to be working fine, but 3 seems to cause issues.  
- The 3 can be local or deployed, or a combination - doesn't seem to make any difference.  
- From the console logs, it looks like when the issue exists, the couch calls are not being made at all.

**Comment by wsmith-nwfsc** [comment]
Looks like this may be specific to bn-couch (not using this in obs-trips yet.) I'm able to run 5 tabs of obs-trips and it all seems OK, so I'll take a look at obs-web next.

**Comment by wsmith-nwfsc** [comment]
Haven't looked at this for a long time. Let's revisit this after I finish converting the remaining libraries to our npm package.
