### ISSUE TITLE
couchdb - OTS can't write to master-dev - missing debriefer role?

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#522]
OTS (dev deployment) can no longer write to Couch Master-Dev DB - did the debriefer role get removed?

**Comment by wsmith-nwfsc** [comment]
What's the error message? (The one Todd sent me earlier was a null error that didn't have anything to do with the DB, line 320 in Trips.vue I think was the culprit)

**Comment by sethgerou-noaa** [comment]
index.js:728 Uncaught (in promise) Error: Error with put request for CouchDB database master-dev at https://nwcdevfram2.nwfsc2.noaa.gov:6984/master-dev/800f861a2dbf141f75a309dfe06ca2e2. 403 Forbidden
    at new t (index.js:728)
    at e.<anonymous> (index.js:248)
    at c (index.js:50)
    at Object.next (index.js:31)
    at index.js:25
    at new Promise (<anonymous>)
    at o (index.js:21)
    at e.checkErrorAndGetBody (index.js:243)
    at e.<anonymous> (index.js:471)
    at c (index.js:50)
t @ index.js:728
(anonymous) @ index.js:248
c @ index.js:50
(anonymous) @ index.js:31
(anonymous) @ index.js:25
o @ index.js:21
e.checkErrorAndGetBody @ index.js:243
(anonymous) @ index.js:471
c @ index.js:50
(anonymous) @ index.js:31
a @ index.js:22
Promise.then (async)
(anonymous) @ OtsTargetDetail.vue?1c63:491
w @ runtime.js:65
(anonymous) @ runtime.js:303
e.<computed> @ runtime.js:117
o @ asyncToGenerator.js:5
s @ asyncToGenerator.js:27
Promise.then (async)
o @ asyncToGenerator.js:15
s @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:23
t @ OtsTargetDetail.vue?1c63:234
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
nt @ vue.runtime.esm.js:1854
Yn.e.$emit @ vue.runtime.esm.js:3882
click @ QBtn.js:63
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Qi.o._wrapper @ vue.runtime.esm.js:6911
XHR failed loading: PUT "https:/

**Comment by wsmith-nwfsc** [comment]
Just checked and none of the permissions have changed recently. Which user is this? I'd verify they have debriefer roles in _users

**Comment by wsmith-nwfsc** [comment]
If it's sgerou-test, it looks like that user is fine (although there's a typo in a role: "perimt owner"

I'd try catching that error and seeing what the detailed message says. Perhaps you're not supplying the newest _rev with your doc?

**Comment by sethgerou-noaa** [comment]
My user:

{
  "_id": "org.couchdb.user:seth.gerou",
  "_rev": "47-0fd74690930a74a8c30fa055bf707457",
  "type": "user",
  "updated": "2019-05-24T15:36:08-07:00",
  "name": "seth.gerou",
  "roles": [
    "observer",
    "captain",
    "staff",
    "perimt owner",
    "provider",
    "debriefer"
  ],
  "password_scheme": "pbkdf2",
  "iterations": 10,
  "derived_key": "116531e959c4a364f5c238d2c0bfea824593a6fd",
  "salt": "123c247f6aa333c815aad65ac97d60a5"
}

**Comment by sethgerou-noaa** [comment]
Ha, thanks for the typo catch.   Will fix.

**Comment by sethgerou-noaa** [comment]
the error in the network tab:
{error: "forbidden", reason: "This database is read-only"}
error: "forbidden"
reason: "This database is read-only"

**Comment by wsmith-nwfsc** [comment]
Odd.

1. Whenever you re-auth, the auth server will set your couchDB roles to whatever ApexUserAdmin says (nothing right now, so it's always the default, "[\"observer\",\"debriefer\"]), so I'm not sure how you've added those roles and had them persist.

2. Unless the validation doc changed, something else is going on, will need to dig further

**Comment by sethgerou-noaa** [comment]
Oh, what I sent was my user doc in fauxton, not what I'm getting back upon login.  No reason to believe they'll persist.

**Comment by wsmith-nwfsc** [comment]
Yes, but the auth server should also be updating your user doc with the roles each time. Taking a closer look...

**Comment by wsmith-nwfsc** [comment]
Ok, I see what's going on:

* The validation doc requires the user to have debriefer role, for master-dev
* We're still waiting on ApexUserAdmin functionality to get real roles. The auth server currently just assigns ['observer'] role to everyone.  Your role changes in _users::seth.gerou are wiped out every time you log in. I just checked and you only have the observer role.
* We created {{-test}} users (e.g. sgerou-test) to allow us to use the dev-auth-server to add different roles to ourselves--this is currently the only way to test roles effectively.
* In the meantime I've updated the auth server to grant everyone ['observer', 'debriefer'] roles but someone changed permissions on Jenkins so that is now breaking, investigating what's happening there next...
* Alternatively we could modify the validation doc to allow 'observers' write access


If you reload your user doc you'd see that you only have the observer role, immediately after you log in, because auth server rewrites the roles on every authorization.
I've modified the auth server to give everyone observer, debriefer roles. This should fix it for you.

We created the -test users so our dev-auth-servers would let us play with roles.  Real users like seth.gerou will have their roles wiped every auth attempt, at this point.

We are waiting on the ApexUserAdmin roles capabilities, until then, I've just hardcoded

**Comment by wsmith-nwfsc** [comment]
OK, now when you auth your "legit" user, you'll also have the debriefer role, this should fix the issue.
Can verify by pasting JWT token into jwt.io:
![image](https://user-images.githubusercontent.com/12972097/59473321-dbc36e00-8df6-11e9-8f5c-b0eb1c2fe5d2.png)

**Comment by sethgerou-noaa** [comment]
nice, Thanks Will!
