### ISSUE TITLE
Catch - 'Edit Species' - only active when an individual species row is selected.  Enables setting of discard reason + moving to another grouping.  Should this allow the changing of species?

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#599]

**Comment by ericbrasseur-NOAA** [comment]
I would say the option to change the species for all underlying records would be a slightly different function than editing the DR or changing WM groups.  It is rare to misid a species so I would isolate that function from normal editing.  It should be an option but a little harder to do.

**Comment by sethgerou-noaa** [comment]
Thanks Eric, that's pretty much what I was thinking.   

Wondering if instead of a 'Delete' button maybe we provide something like a 'Modify' button that includes both change species (that changes the species associated with the underlying data) and delete functionality (if there's no underlying data), and includes all necessary warnings and restrictions.

**Comment by sethgerou-noaa** [comment]
In terms of edit functionality, here's what I'm thinking...

If a species row is selected, 'Edit' would be limited to Weight Method, Disposition, and Discard Reason (changing Weight Method and/or disposition would move the species to a different grouping)

If a grouping row (Disposition/Weight Method combo) is selected, should the Observer be able to edit the entire grouping?  Changing the weight method/disposition of all species that are currently D3 to R3 for example?  Or should they have to edit each species individually?

**Comment by ericbrasseur-NOAA** [comment]
I see 2 things here:
The most common change on the species level is discard reason.  So perhaps changing the DR can be allowed without specifically selecting modify.
Here is what we have now:
Catch category (CC) = weight method (WM) grouping
to edit a wm group requires explicit choice and is restricted in changes.  Normally selecting a group simply opens that group for species entry, once it is created, user must select modify first then the group.  If there are species and weights in a group already, changing the wm or disposition is extremely suspect.
![image](https://user-images.githubusercontent.com/45770674/61074271-2f13e680-a3cc-11e9-81c7-5a3b68eb3ac9.png)
![image](https://user-images.githubusercontent.com/45770674/61074632-ff191300-a3cc-11e9-97c1-35c5b865ab9b.png)

If I had been sampling already that means I was working in a specific way based on the wm selected.  To alter that after the fact is extremely rare and could change the calculations which could cause a cascade of errors. I would by default not allow that change and instead leave that as exclusively a debriefer function (though after field testing it could eventually be expanded if needed and we haven't needed it yet)

That said, it is entirely possible that a user accidentally puts a species in the wrong group.  This currently primarily happens when transcribing as it is much harder to do this wrong in the field due to work flow.  In general there are very few wm groups used at the same time.  Retained is often entered hours later directly from a logbook.  Other wm groups are species specific (Halibut). And visual groups are for very large species. The other WM 3,15,20,21, are generally used one at a time (ie you will rarely see a 3 and 21 in the same haul)
![image](https://user-images.githubusercontent.com/45770674/61074650-093b1180-a3cd-11e9-8103-c4351793f63d.png)
![image](https://user-images.githubusercontent.com/45770674/61074847-81093c00-a3cd-11e9-9a77-472bad231634.png)
![image](https://user-images.githubusercontent.com/45770674/61075578-2375ef00-a3cf-11e9-9a08-ad61e9704060.png)

The discard reason is generally 13, but sometimes the vessel changes it's mind and that changes or a size restriction came into play (lingcod dr 16).  So changing a species dr should be as simple as highlighting the species and pressing a different dr.  No calculations are affected and this is what we currently do.
For other changes such as disposition and wm group a modify button would be required. I would say once the species is highlighted a modify button becomes available. Other than DR, nothing can be edited unless modify is pressed.

When pressed they can change the disposition and wm (ie assign them to another group)  If no underlying data, simply allow the change.  If there is underlying data check to see if any rules are violated (ie cannot move a halibut to a retained category on a trawler.) and prompt the user of the ramification of the change.  Example I want to move 500lbs of hake from a wm 20 retained to a wm 21 retained.  Prompt would say are you sure you want to do this?  Expansion of species comp will be affected.

Another possibility is to allow a user to grab a species and move it to a different group.  Confirmations would be required of course.
