### ISSUE TITLE
Jenkins: Standardize way for secrets storage in Jenkins deployments

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/boatnet#642]
Jenkins has a "secrets" functionality, but without full admin access we can't use it easily.
Determine a standard way to handle these, similar to how dbConfig.json is configured now.

**Comment by SaOgaz-NOAA** [comment]
We were not able to use jenkin's secrets (denied by sys admins, forget the specific reason, I think it was just because of the admin access requirement). We have the dbconfigs mostly standardized. I don't think it's worth the effort right not to go back and change any jobs that are slightly different. BUT we should keep this in mind when making new jobs.
