### ISSUE TITLE
lookups editor

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#989]

**Comment by sethgerou-noaa** [comment]
Lookups editor now driven by models and is pretty well baked.
Will likely get some tweaks pending outcome of discussion next week.
to do: enchance lookups editor to fully support editing boatnet configs - created a new ticket specifically for that.

**Comment by toddhay-NOAA** [comment]
@sethgerou-noaa , I had a look at the Lookup Editor and really like what I see, nice work on this.  Here is some feedback:

- [ ] Remove Get Doc Types - Please remove this button and have the list of Doc Types auto-populate once the Lookup Editor button is clicked
- [ ] Rename Doc Types: label to Lookups: - this will be more intuitive to our data stewards
- [ ] Sorting based on legacy values - For a number of the lookup types, you seem to be sorting on a lookupVal from the legacy section.  I guess my thinking is, if it is so important that we're sorting based on this value, is it really a legacy value?  However, having said that, I'm not sure we should sort on it as we already determined that it was best put in the legacy section and so wasn't critical going forward.  Thoughts?
- [ ] Port Docs - I'm noticing that the port names are all capitalized.  I'm assuming that is coming directly from CouchDB, yes?  If so, @NickShafferNOAA, please adjust the Port documents so that they are title case
- [ ] Program Docs - You have a leading hyphen in the names, which I'm guessing is because you're trying to put a lookupVal at the beginning.  I would probably just use the name for the Program Docs listing
- [ ] Saved-Selections Doc - Appears blank, what is this data anyways?  FYI: @NickShafferNOAA - might have an ETL issue here
- [ ] Species Docs - no name appears in the Species Docs listing.  Please use the common name and sort by that for now
- [ ] Survey Docs - I noticed that Survey is the only Doc Types that is capitalized in the Doc Types listing.  Please lowercase that like the others, or perhaps this is a @NickShafferNOAA ETL fix as well.  Please advise as to what you recommend here.
- [ ] Tally-Record Docs - It's showing two blank-named documents.  What are these supposed to be?
- [ ] Trip-Selection Docs - These look like actual trip selections and not really lookups, so I think they should be excluded from the lookups editor
